### ISSUE TITLE
Snippet completion box doesn't show up

### ISSUE THREAD

**Issue by jasonmng** [dev4dev/blade-snippets#22]
If I start typing ext, I expect to see a completion box showing snippets matching ext, however this box does not show.  Any thoughts on how I can fix this? The snippet will insert itself if I tab after typing in "ext"

**Comment by dev4dev** [comment]
What's wrong with using `Tab` key?

**Comment by jasonmng** [comment]
Using the tab key becomes a problem when I can only remember that the snippet begins with and 'e' or 'ex' and so on.  Do you get the same behavior—not seeing the completion box—in your editor?

**Comment by dev4dev** [comment]
yep, autocompletion box doesn't appear. is that case true for other languages like html or css in sublime?
