### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by mazedulislamkhan** [dev4dev/blade-snippets#25]
Hi,
I'm using this package with the Sublime Text 3. However, it's not working for me. It doesn't autocomplete after I type the shortcode and hit TAB.

**Comment by ozgrozer** [comment]
I got same problem.

**Comment by dev4dev** [comment]
It works when your file's syntax set to 
<img width="473" alt="screenshot 2016-01-08 13 28 27" src="https://cloud.githubusercontent.com/assets/722407/12196999/c602b290-b60b-11e5-8015-03a0d57fb271.png">

**Comment by mazedulislamkhan** [comment]
Unfortunately, there's nothing similar `Laravel Blade` when I try to set blade syntax like the way you're doing. :(

**Comment by ozgrozer** [comment]
No it doesn't work.

![](http://i.imgur.com/GwiBbpp.png)

**Comment by dev4dev** [comment]
![blade](https://cloud.githubusercontent.com/assets/722407/12197631/3d40e9bc-b611-11e5-80d5-2bd0248024fb.gif)

**Comment by ozgrozer** [comment]
Trying same things but nothing happen.

![3bktly2cnx](https://cloud.githubusercontent.com/assets/651938/12198074/720eed3e-b615-11e5-8c00-5ba2a1455fc6.gif)

**Comment by mazedulislamkhan** [comment]
Thank you @dev4dev man. It's working for me now. Didn't know I've to also install `Laravel Blade Highlighter` (y)

**Comment by dev4dev** [comment]
@mazedulislamkhan you are welcome, it was so a long time ago, that I've forgot about this dependency, I don't know why I didn't include it in documentation.

@ozgrozer man, I have no idea why this could happen to you =(
maybe to try clean install

**Comment by deweller** [comment]
This stopped working for me.

I think the problem is that Laravel Blade Highlighter uses a scope of `text.blade` and this snippets package is looking for a scope of `text.html.laravel-blade`.

Is it feasible to change the scope from:
`<scope>text.html.laravel-blade</scope>`
to
`<scope>text.html.laravel-blade,text.blade</scope>`
?

Thanks

**Comment by redgluten** [comment]
Yep, I’ve made a PR, [we may need to reinstall the package](https://forum.sublimetext.com/t/snippets-stopped-working/17450/5) though.
